---
title: "Biomass and PSF"
author: "MD"
date: '`r Sys.Date()`'
output: 
 html_document:
   toc: true
   toc_float: true
   editor_options:
   chunck_output_type: console
   chunk_output_type: console
---
# Setup
 
## Load libraries 
```{r, include = F}
library(tidyverse) # contains ggplot, dplyr, etc
library(car) # for Anova function
library(emmeans) # emmeans and CLD
library(patchwork) # agglomerates facets from graphs
library(agricolae) # runs main effect TUkey test
```

## Load data
```{r, echo=F}
d <- read.csv('Data/Biomass_TimeCourse.csv') %>% 
  filter(.,!is.na(Shoot_Biomass_g)) %>% 
  filter(.,!is.na(Root_Biomas_g)) 



d <- d %>%
mutate(Harvest = as_factor(Harvest)) %>%
mutate(Harvest = fct_relevel(Harvest, "Seedling", "Early_Vegetative", "Late_Vegetative", "Early_Flower", "Late_Flower"))
table(d$Harvest)
d<- select(d, Sample_ID, Rep, Domestication, Harvest, Fertilization, Shoot_Biomass_g, Root_Biomas_g)

head(d)
par(mfrow=c(2,2))
options(contrasts = c("contr.sum", "contr.poly"))
```

# Analysis
## Shoot
### Model fitting

```{r}
mod <- lm(log(Shoot_Biomass_g) ~  Fertilization*Domestication*Harvest, 
           data = d)
plot(mod)

Anova(mod, type = 3)
t<-HSD.test(mod, "Fertilization");t
t<-HSD.test(mod, "Domestication");t
t<-HSD.test(mod, "Harvest");t

emmip(mod, Domestication ~ Harvest | Fertilization, CIs = TRUE, type = "response")# type = response shows backtransformed 

emmeans(mod, pairwise ~ Domestication|Harvest|Fertilization)

emmeans(mod, ~ Fertilization*Domestication*Harvest, type = "response")
df <- as.data.frame(emmeans(mod, ~ Fertilization*Domestication*Harvest, type = "response"))

res <- emmeans(mod, list(pairwise ~ Fertilization*Domestication*Harvest), adjust = "fdr")
plot(res[[1]], horizontal=F)
groups <- data.frame(multcomp::cld(res[[1]], adjust='fdr', Letters=c("abcdefghijklmnopqrstuvwxy"), decreasing=T)) %>% 
  select(., Fertilization, Domestication, Harvest, .group)
df <- inner_join(df,groups, by = c('Fertilization', 'Domestication', 'Harvest'))

names(df)[names(df) == '.group'] <- 'letters'
df$letters <- gsub(' ','',df$letters)
```

### Data visualization
```{r}
df.f <- filter(df, Fertilization == "Fertilized")
df.u <- filter(df, Fertilization == "Unfertilized")
```

```{r}
p_shoot_u <- ggplot(aes(x=Harvest, y=response), data = df.u) +
  geom_line(aes(color=Domestication, group=Domestication),
            stat='summary',fun='mean',linewidth=1) +
  geom_errorbar(width=0.25,alpha=0.5,
                aes(ymin = lower.CL, ymax = upper.CL, 
                    group=Domestication,color=Domestication))+
  scale_color_manual(values = c('darkblue','darkorange2'))+
  geom_text(aes(label = letters),position=position_dodge(0.9), vjust = -3, hjust = -0.2) +
  theme_classic()+
  labs(y="Shoot Biomass (g)")+
  theme(legend.title = element_blank(),
        legend.position = 'right',
        axis.text = element_text(color='black'),
        axis.title.x = element_blank());p_shoot_u
#ggsave(plot=p_shoot, '../../Manuscript/figs/R_output/shoot_biomass.png', width = 8, height = 4)
```

```{r}
p_shoot_f <- ggplot(aes(x=Harvest, y=response), data = df.f) +
  geom_line(aes(color=Domestication, group=Domestication),
            stat='summary',fun='mean',linewidth=1) +
  geom_errorbar(width=0.25,alpha=0.5,
                aes(ymin = lower.CL, ymax = upper.CL, 
                    group=Domestication,color=Domestication))+
  scale_color_manual(values = c('darkblue','darkorange2'))+
  geom_text(aes(label = letters),position=position_dodge(0.9), vjust = -3, hjust = -0.2) +
  theme_classic()+
  labs(y="Shoot Biomass (g)")+
  theme(legend.title = element_blank(),
        legend.position = 'right',
        axis.text = element_text(color='black'),
        axis.title.x = element_blank());p_shoot_f
#ggsave(plot=p_shoot, '../../Manuscript/figs/R_output/shoot_biomass.png', width = 8, height = 4)
```

## Root

### Model fitting
```{r}
mod <- lm(log(Root_Biomas_g) ~  Fertilization*Domestication*Harvest, 
           data = d)
plot(mod)
Anova(mod, type = 3)
t <- HSD.test(mod, "Fertilization");t
t <- HSD.test(mod, "Domestication");t
t <- HSD.test(mod, "Harvest");t
emmip(mod, Domestication ~ Harvest | Fertilization, CIs = TRUE, type = "response")# type = response shows backtransformed 

emmeans(mod, pairwise ~ Domestication|Harvest|Fertilization)

df <- as.data.frame(emmeans(mod, ~ Fertilization*Domestication*Harvest, type = "response"))

res <- emmeans(mod, list(pairwise ~ Harvest*Fertilization*Domestication), adjust = "fdr")
plot(res[[1]], horizontal=T)
groups <- data.frame(multcomp::cld(res[[1]], adjust='fdr', Letters=c("abcdefghijklmnopqrstuvwxy"), decreasing=T)) %>% 
  select(., Fertilization, Domestication, Harvest, .group)
df <- inner_join(df,groups, by = c('Fertilization', 'Domestication', 'Harvest'))

names(df)[names(df) == '.group'] <- 'letters'
df$letters <- gsub(' ','',df$letters)
```

### Data visualization
```{r}
df.rf <- filter(df, Fertilization == "Fertilized")
df.ru <- filter(df, Fertilization == "Unfertilized")
```

```{r}
p_root_u <- ggplot(aes(x=Harvest, y=response), data = df.ru) +
  geom_line(aes(color=Domestication, group=Domestication),
            stat='summary',fun='mean',linewidth=1) +
  geom_errorbar(width=0.25,alpha=0.5,
                aes(ymin = lower.CL, ymax = upper.CL, 
                    group=Domestication,color=Domestication))+
  scale_color_manual(values = c('darkblue','darkorange2'))+
  geom_text(aes(label = letters),position=position_dodge(0.9), vjust = -3, hjust = -0.2) +
  theme_classic()+
  labs(y="Root Biomass (g)")+
  theme(legend.title = element_blank(),
        legend.position = 'right',
        axis.text = element_text(color='black'),
        axis.title.x = element_blank());p_root_u
#ggsave(plot=p_root_u, '../../Manuscript/figs/R_output/root_biomass_unfert.png', width = 8, height = 4)

```


```{r}
p_root_f <- ggplot(aes(x=Harvest, y=response), data = df.rf) +
  geom_line(aes(color=Domestication, group=Domestication),
            stat='summary',fun='mean',linewidth=1) +
  geom_errorbar(width=0.25,alpha=0.5,
                aes(ymin = lower.CL, ymax = upper.CL, 
                    group=Domestication,color=Domestication))+
  scale_color_manual(values = c('darkblue','darkorange2'))+
  geom_text(aes(label = letters),position=position_dodge(0.9), vjust = -3, hjust = -0.2) +
  theme_classic()+
  labs(y="Root Biomass (g)")+
  theme(legend.title = element_blank(),
        legend.position = 'right',
        axis.text = element_text(color='black'),
        axis.title.x = element_blank());p_root_f
#ggsave(plot=p_root_u, '../../Manuscript/figs/R_output/root_biomass_unfert.png', width = 8, height = 4)

```

```{r}
p_shootroot_u <-p_shoot_u/p_root_u + plot_layout(axes = "collect") + plot_layout(guides = "collect")
#ggsave(plot=p_shootroot_u, '../../Manuscript/figs/R_output/shoot_root_unfert.png', width = 8, height = 6)

```
