---
title: "dbRDA_permanova"
author: "MD"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

# Load libraries
```{r}
library(vegan)
library(pairwiseAdonis)
library(RColorBrewer)
library(microbiomeMarker)
library(tidyverse)
library(phyloseq)
library(readxl)
```

# Read in data and create data OTU/sample data tables
```{r}
P.rel <- readRDS('phyloseq/P.Time.rel.RDS') %>% 
  subset_samples(., Reads.16S > 10000)

d <- data.frame(sample_data(P.rel))

data <- data.frame(t(otu_table(P.rel)))
data <- decostand(data, method='hellinger')

dist <- vegdist(data, method='bray')
```


# perMANOVA with pairwise comparisons
```{r}
adonis2(dist ~  Stage*Fertilization*Domestication, data=d, perm=999)

pairwise.adonis(dist,factors=d$Fertilization, p.adjust.m = "fdr")
pairwise.adonis(dist,factors=d$Domestication, p.adjust.m = "fdr")
pairwise.adonis(dist,factors=d$Stage, p.adjust.m = "fdr")
```

# Create ordination model, get eigenvalues
```{r}
ord <- capscale(dist ~ Stage*Fertilization*Domestication, data=d)
ev <- eigenvals(ord)
Axis1_exp = round(ev[1] / sum(ev) * 100, 1)
Axis2_exp = round(ev[2] / sum(ev) * 100, 1)
```

# Create dataframe for ordination plot
```{r}
axes <- as.data.frame(vegan::scores(ord, display="sites", choices=c(1:2)))
axes <- cbind(d, axes)
axes$Stage <- as.character(axes$Stage)

level_order <- factor(axes$Stage, levels = c('Seedling', 'Early_Vegetative', 'Late_Vegetative', 'Early_Flower', 'Late_Flower'))
```

# Create plot

## color by developmental stage
```{r}
p<-ggplot(data=axes, aes(x=CAP1, y=CAP2, fill=level_order, shape=Domestication)) +
  geom_point(size=6,color='black') +
  stat_ellipse(aes(group= level_order, color= level_order), type='t', level=0.95) +
  scale_fill_manual(values = c('firebrick','darkorange','darkslategray1','darkblue','dodgerblue'))+
  scale_color_manual(values = c('firebrick','darkorange','darkslategray1','darkblue','dodgerblue'))+
  scale_shape_manual(values=c(21,22)) +
  guides(fill = guide_legend(
    override.aes=list(shape = rep(21)))) +
  labs(x=paste0('CAP1 (', Axis1_exp, '%)'), 
       y=paste0('CAP2 (', Axis2_exp, '%)'),
       alpha='none') +
  theme_classic();p
```

## Color by domestication
```{r}

p<-ggplot(data=axes, aes(x=CAP1, y=CAP2, fill=Domestication, shape=level_order)) +
  geom_point(size=6,color='black') +
  stat_ellipse(aes(group= Domestication, color= Domestication), type='t', level=0.95) +
  scale_fill_manual(values = c('firebrick','darkorange'))+
  scale_color_manual(values = c('firebrick','darkorange'))+
  scale_shape_manual(values=c(21,22,23,24,25)) +
  guides(fill = guide_legend(
    override.aes=list(shape = rep(21)))) +
  labs(x=paste0('CAP1 (', Axis1_exp, '%)'), 
       y=paste0('CAP2 (', Axis2_exp, '%)'),
       alpha='none') +
  theme_classic();p
```

# Create ordination for unconstrained PCoA
```{r}
sample_data(P.rel)$Stage <- as.factor(sample_data(P.rel)$Stage)

GloPa.pcoa = ordinate(P.rel, method="PCoA", distance=dist)
```

## skree plot
```{r}
plot_scree(GloPa.pcoa, "Scree plot for Global Patterns PCoA")
```

## pcoa plot
```{r}
p <- plot_ordination(P.rel, GloPa.pcoa, "samples", color="Stage") + 
  geom_point(size=5) +
  scale_color_manual(values = c('firebrick','darkorange','darkslategray1','darkblue','dodgerblue'))+
  stat_ellipse(aes(group= Stage, color= Stage), type='t', level=0.95) +
  theme_classic();p
```

