---
title: "P Concentration and Olsen P"
author: "MD"
date: "`r Sys.Date()`"
output: 
 html_document:
   toc: true
   toc_float: true
   editor_options:
     chunk_output_type: console
   chunck_output_type: console
   chunk_output_type: console
---

```{r}
library(tidyverse)
library(agricolae)
library(emmeans)
library(patchwork)
library(agricolae)
library(car)
```


```{r}
d <- read.csv('Data/Soil_M3_Total.csv')

d <- d %>%
mutate(Harvest_Stage = as_factor(Harvest_Stage)) %>%
mutate(Harvest_Stage = fct_relevel(Harvest_Stage, "Seedling", "Early_Vegetative", "Late_Vegetative", "Early_Flower", "Late_Flower"))
table(d$Harvest_Stage)


head(d)
par(mfrow=c(2,2))
options(contrasts = c("contr.sum", "contr.poly"))
```

# M3 Concentration

```{r}
mod <- lm(log(Phosphorus.M3.ppm.P) ~  Domestication*Harvest_Stage, data = d)

plot(mod)
Anova(mod, type = 3)
t <- HSD.test(mod, "Domestication");t


summary(aov(mod))
emmip(mod, Domestication ~ Harvest_Stage , CIs = TRUE, type = "response")# type = response shows backtransformed 

emmeans(mod, pairwise ~ Domestication|Harvest_Stage)

df <- as.data.frame(emmeans(mod, ~ Domestication*Harvest_Stage, type = "response"))

res <- emmeans(mod, list(pairwise ~ Domestication*Harvest_Stage), adjust = "fdr")
plot(res[[1]], horizontal=T)
groups <- data.frame(multcomp::cld(res[[1]], adjust='fdr', Letters=c("abcdefghijklmnopqrstuvwxy"), decreasing=T)) %>% 
  select(.,  Domestication,Harvest_Stage, .group)
df <- inner_join(df,groups, by = c( 'Domestication', 'Harvest_Stage'))

names(df)[names(df) == '.group'] <- 'letters'
df$letters <- gsub(' ','',df$letters)
```

```{r}
p_m3 <- ggplot(aes(x=Harvest_Stage, y=response), data = df) +
  geom_line(aes(color=Domestication, group=Domestication),
            stat='summary',fun='mean',size=1) +
  geom_errorbar(width=0.25,alpha=0.5,
                aes(ymin = lower.CL, ymax = upper.CL, 
                    group=Domestication,color=Domestication))+
  scale_color_manual(values = c('darkblue','darkorange2'))+
  geom_text(aes(label = letters),position=position_dodge(0.9), vjust = -3, hjust = -0.2) +
  theme_classic()+
  labs(y="Mehlich-3 Phosphorus Concentration (mg/kg)")+
  theme(legend.title = element_blank(),
        legend.position = 'right',
        axis.text = element_text(color='black'),
        axis.title.x = element_blank());p_m3
#ggsave(plot=p_m3, '../../Manuscript/figs/R_output/m3_p.png', width = 8, height = 4)
```

