---
title: "P Assays"
author: "MD"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
library(tidyverse)
library(agricolae)
library(emmeans)
library(patchwork)
library(agricolae)
library(car)
```

```{r}
d <- read.csv("Data/P_Sol_Index.csv") 
d$Exudate <- gsub("None", "No_Exudate", d$Exudate)
par(mfrow=c(2,2))
options(contrasts = c("contr.sum", "contr.poly"))
```

```{r}

mod <- lm((P_index_96) ~  P_Source*Exudate, data = d)

plot(mod)
aov.mod <- aov(mod)
summary(aov.mod)
t <- HSD.test(mod, "Exudate");t
```

```{r}
emmeans(mod, pairwise ~ P_Source|Exudate)

df <- as.data.frame(emmeans(mod, ~ P_Source*Exudate))

res <- emmeans(mod, list(pairwise ~ P_Source*Exudate), adjust = "fdr")
plot(res[[1]], horizontal=T)
groups <- data.frame(multcomp::cld(res[[1]], adjust='fdr', Letters=c("abcdefghijklmnopqrstuvwxy"), decreasing=T)) %>% 
  select(.,  P_Source,Exudate, .group)
df <- inner_join(df,groups, by = c( 'P_Source', 'Exudate'))

names(df)[names(df) == '.group'] <- 'letters'
df$letters <- gsub(' ','',df$letters)
```


```{r}
test_df <- read.csv("Data/test_df.csv")
df_all <- rbind(df, test_df)

df_all <- df_all %>%
mutate(Exudate = as_factor(Exudate)) %>%
mutate(Exudate = fct_relevel(Exudate, "Glycerol_Monostearate", "1_Stearoyl_Rac_Glycerol","Trehalose", "1-Mono-Palmitin",  "Lauric Acid", "Dodecanol", "No_Exudate"))
table(df_all$Exudate)
```

```{r}
p <- ggplot(aes(x=Exudate, y=emmean,fill=Exudate), data = df_all) +
  geom_col(position = 'dodge') +
  facet_wrap(~P_Source)+
  geom_errorbar(width=0.25,alpha=0.5,
                aes(ymin = lower.CL, ymax = upper.CL, group = P_Source), position =position_dodge(0.9))+
  scale_fill_manual(values = c('firebrick4','chocolate','khaki3','chartreuse4','black','black','gray40'))+
  geom_text(aes(label = letters),position=position_dodge(0.9), vjust = -3, hjust = -0.2) +
  theme_classic()+
  labs(y="Phosphorus Solubilization Index (cm/cm)")+
  theme(legend.title = element_blank(),
        legend.position = 'none',
        strip.text = element_blank(),
        axis.text = element_text(color='black'),
        axis.title.x = element_blank(),
        axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5));p
ggsave(plot = p, "../Manuscript/figs/R_output/p_assay.png", width = 8, height = 5)
```
