---
title: "P Concentration and Olsen P"
author: "MD"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
library(tidyverse)
library(agricolae)
library(emmeans)
library(patchwork)

```


```{r}
d <- read.csv('Data/P_Concentration.csv') %>% 
  filter(., Harvest != "Seedling")

d <- d %>%
mutate(Harvest = as_factor(Harvest)) %>%
mutate(Harvest = fct_relevel(Harvest, "Early_Vegetative", "Late_Vegetative", "Early_Flower", "Late_Flower"))
table(d$Harvest)

d <- d %>%
mutate(Fertilization = as_factor(Fertilization)) %>%
mutate(Fertilization = fct_relevel(Fertilization, "Unfertilized", "Fertilized"))

head(d)
par(mfrow=c(2,2))
options(contrasts = c("contr.sum", "contr.poly"))
```

# Concentration

```{r}
mod <- lm(log(P.ppm.) ~  Fertilization*Domestication*Harvest, data = d)

plot(mod)


summary(aov(mod))
#Anova(mod, type = 3)
emmip(mod, Domestication ~ Harvest | Fertilization, CIs = TRUE, type = "response")# type = response shows backtransformed 

emmeans(mod, pairwise ~ Domestication|Harvest|Fertilization)

emmeans(mod, ~ Fertilization*Domestication, type = "response")
df <- as.data.frame(emmeans(mod, ~ Fertilization*Domestication*Harvest, type = "response"))

res <- emmeans(mod, list(pairwise ~ Fertilization*Domestication*Harvest), adjust = "fdr")
plot(res[[1]], horizontal=T)
groups <- data.frame(multcomp::cld(res[[1]], adjust='fdr', Letters=c("abcdefghijklmnopqrstuvwxy"), decreasing=T)) %>% 
  select(., Fertilization, Domestication,Harvest, .group)
df <- inner_join(df,groups, by = c('Fertilization', 'Domestication', 'Harvest'))

names(df)[names(df) == '.group'] <- 'letters'
df$letters <- gsub(' ','',df$letters)
```

```{r}
p_conc <- ggplot(aes(x=Harvest, y=response), data = df) +
  geom_line(aes(color=Domestication, group=Domestication),
            stat='summary',fun='mean',size=1) +
  geom_errorbar(width=0.25,alpha=0.5,
                aes(ymin = lower.CL, ymax = upper.CL, 
                    group=Domestication,color=Domestication))+
  scale_color_manual(values = c('darkblue','darkorange2'))+
  geom_text(aes(label = letters),position=position_dodge(0.9), vjust = -3, hjust = -0.2) +
  facet_wrap(~Fertilization, ncol=2)+
  theme_classic()+
  labs(y="Shoot Phosphorus Concentration (mg/kg)")+
  theme(legend.title = element_blank(),
        legend.position = 'right',
        axis.text.x=element_text(angle = 90),
        axis.text = element_text(color='black'),
        axis.title.x = element_blank());p_conc
#ggsave(plot=p, 'output/olsen_p.png', width = 12, height = 6)
```

# Uptake

```{r}
mod <- lm(log(P_content) ~  Fertilization*Domestication*Harvest, data = d)

plot(mod)


summary(aov(mod))
#Anova(mod, type = 3)
emmip(mod, Domestication ~ Harvest | Fertilization, CIs = TRUE, type = "response")# type = response shows backtransformed 

emmeans(mod, pairwise ~ Domestication|Harvest|Fertilization)

emmeans(mod, ~ Fertilization*Domestication, type = "response")
df <- as.data.frame(emmeans(mod, ~ Fertilization*Domestication*Harvest, type = "response"))

res <- emmeans(mod, list(pairwise ~ Fertilization*Domestication*Harvest), adjust = "fdr")
plot(res[[1]], horizontal=F)
groups <- data.frame(multcomp::cld(res[[1]], adjust='fdr', Letters=c("abcdefghijklmnopqrstuvwxy"), decreasing=T)) %>% 
  select(., Fertilization, Domestication,Harvest, .group)
df <- inner_join(df,groups, by = c('Fertilization', 'Domestication', 'Harvest'))

names(df)[names(df) == '.group'] <- 'letters'
df$letters <- gsub(' ','',df$letters)
```

```{r}
p_up <- ggplot(aes(x=Harvest, y=response), data = df) +
  geom_line(aes(color=Domestication, group=Domestication),
            stat='summary',fun='mean',size=1) +
  geom_errorbar(width=0.25,alpha=0.5,
                aes(ymin = lower.CL, ymax = upper.CL, 
                    group=Domestication,color=Domestication))+
  scale_color_manual(values = c('darkblue','darkorange2'))+
  geom_text(aes(label = letters),position=position_dodge(0.9), vjust = -3, hjust = -0.2) +
  facet_wrap(~Fertilization, ncol=2)+
  theme_classic()+
  labs(y="Shoot Phosphorus Uptake (mg)")+
  theme(legend.title = element_blank(),
        legend.position = 'right',
        axis.text.x=element_text(angle = 90),
        axis.text = element_text(color='black'),
        axis.title.x = element_blank());p_up
#ggsave(plot=p, 'output/olsen_p.png', width = 12, height = 6)
```

# Olsen P
```{r, echo=F}
d <- read.csv('Data/Olsen-P.csv') %>% 
  filter(., !is.na(mg.kg))

d <- d %>%
mutate(Harvest = as_factor(Harvest)) %>%
mutate(Harvest = fct_relevel(Harvest, "Seedling", "Early_Vegetative", "Late_Vegetative", "Early_Flower", "Late_Flower"))
table(d$Harvest)

d <- d %>%
mutate(Fertilization = as_factor(Fertilization)) %>%
mutate(Fertilization = fct_relevel(Fertilization, "Unfertilized", "Fertilized"))

head(d)
par(mfrow=c(2,2))
options(contrasts = c("contr.sum", "contr.poly"))

```



```{r}
d <- d[-111,]

d <- d[-9,]
mod <- lm(sqrt(mg.kg) ~  Fertilization*Domestication*Harvest, 
           data = d)

plot(mod)


summary(aov(mod))
#Anova(mod, type = 3)
emmip(mod, Domestication ~ Harvest | Fertilization, CIs = TRUE, type = "response")# type = response shows backtransformed 

emmeans(mod, pairwise ~ Domestication|Harvest|Fertilization)

emmeans(mod, ~ Fertilization*Domestication, type = "response")
df <- as.data.frame(emmeans(mod, ~ Fertilization*Domestication*Harvest, type = "response"))

res <- emmeans(mod, list(pairwise ~ Fertilization*Domestication*Harvest), adjust = "fdr")
plot(res[[1]], horizontal=F)
groups <- data.frame(multcomp::cld(res[[1]], adjust='fdr', Letters=c("abcdefghijklmnopqrstuvwxy"), decreasing=T)) %>% 
  select(., Fertilization, Domestication,Harvest, .group)
df <- inner_join(df,groups, by = c('Fertilization', 'Domestication', 'Harvest'))

names(df)[names(df) == '.group'] <- 'letters'
df$letters <- gsub(' ','',df$letters)
```

### Data visualization
```{r}
p_op <- ggplot(aes(x=Harvest, y=response), data = df) +
  geom_line(aes(color=Domestication, group=Domestication),
            stat='summary',fun='mean',size=1) +
  geom_errorbar(width=0.25,alpha=0.5,
                aes(ymin = lower.CL, ymax = upper.CL, 
                    group=Domestication,color=Domestication))+
  scale_color_manual(values = c('darkblue','darkorange2'))+
  geom_text(aes(label = letters),position=position_dodge(0.9), vjust = -3, hjust = -0.2) +
  facet_wrap(~Fertilization, ncol=2)+
  theme_classic()+
  labs(y="Olsen Phosphorus Concentration (mg/kg)")+
  theme(legend.title = element_blank(),
        legend.position = 'right',
        axis.text = element_text(color='black'),
        axis.title.x = element_blank());p_op
#ggsave(plot=p, 'output/olsen_p.png', width = 12, height = 6)
```


```{r}
(p_conc+p_up)/p_op  + plot_layout(guides = "collect")
```










```{r}
d.sub <- filter(d, Harvest != 'Early_Veg')
mod <- lm((P.ppm.) ~  Harvest*Fertilization*Domestication, data=d.sub)
par(mfrow=c(2,2))
plot(mod)
summary(mod)
co <- mod$coefficients

level_order <- factor(d.sub$Harvest, levels = c('Late_Veg','Early_Flower',"Late_Flower","Fruit"))
p <- ggplot(aes(group=Fertilization,x=level_order, y=(P.ppm.)), data = d.sub) +
  geom_hline(yintercept = 0,color='gray50')+
  geom_line(stat='summary',fun='mean',color='black',size=1) +
  geom_smooth(aes(fill=Fertilization, color=Fertilization))+
  scale_fill_manual(values = c('#3498db','#f39c12'))+
  scale_color_manual(values = c('#3498db','#f39c12'))+
  facet_wrap(~Domestication, ncol=2)+
  theme_classic()+
  labs(y="Log-Transformed Root Biomass")+
  theme(legend.title = element_blank(),
        legend.position = 'right',
        axis.text = element_text(color='black'),
        axis.title.x = element_blank());p

p <- ggplot(aes(group=Domestication,x=level_order, y=(P.ppm.)), data = d.sub) +
  geom_hline(yintercept = 0,color='gray50')+
  geom_line(stat='summary',fun='mean',color='black',size=1) +
  geom_smooth(aes(fill=Domestication, color=Domestication))+
  scale_fill_manual(values = c('#3498db','#f39c12'))+
  scale_color_manual(values = c('#3498db','#f39c12'))+
  facet_wrap(~Fertilization, ncol=2)+
  theme_classic()+
  labs(y="Log-Transformed Root Biomass")+
  theme(legend.title = element_blank(),
        legend.position = 'right',
        axis.text = element_text(color='black'),
        axis.title.x = element_blank());p

```

```{r}

#t2
mod <- lm((P.ppm.) ~  Domestication*Fertilization, data=t2)
par(mfrow=c(2,2))
plot(mod)
aov.mod <- aov(mod)
summary(aov.mod)
t<-HSD.test(mod, "Domestication");t
t<-HSD.test(mod, "Fertilization");t
res <- emmeans(mod, list(pairwise ~ Domestication*Fertilization), adjust = "fdr")
res
plot(res[[1]], horizontal=F)
groups <- data.frame(multcomp::cld(res[[1]], adjust='fdr', Letters=c("abcdefghijklmnopqrstuvwxy"), decreasing=T))
groups <- groups %>%
  arrange(Fertilization, Domestication)

sum_shoot <-summarise(group_by(t2, Domestication,Fertilization),
  n = n(),
  mean = mean((P.ppm.)),
  sd = sd((P.ppm.)),
  se = sd/sqrt(n))  %>% 
  left_join(.,groups, by = c('Fertilization', 'Domestication'))
sum_shoot$.group <- gsub(' ','',sum_shoot$.group)

names(sum_shoot)[names(sum_shoot) == '.group'] <- 'letters'

p2<-ggplot(sum_shoot, aes(Domestication, mean, fill = Fertilization)) +
  geom_col(position = 'dodge') +
  geom_text(aes(label = letters),position=position_dodge(0.9), vjust = -.5, hjust = -0.2) +
  scale_fill_manual(values = c('#3498db','#f39c12'))+
  labs(y='Shoot P (mg/kg)')+
  geom_errorbar(aes(ymin = mean-se, ymax = mean+se),position=position_dodge(0.9), width = .25)+
  ggtitle(label = 'Late Vegetative')+
  theme(axis.text=element_text(size=14, colour = "black"), 
        axis.title=element_text(size=12,face="bold"),
        axis.line = element_line(colour = "black"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        panel.background = element_blank(),
        axis.title.x = element_blank(),
       legend.position = 'none');p2
# t3
mod <- lm((P.ppm.) ~  Domestication*Fertilization, data=t3)
par(mfrow=c(2,2))
plot(mod)
aov.mod <- aov(mod)
summary(aov.mod)
t<-HSD.test(mod, "Domestication");t
t<-HSD.test(mod, "Fertilization");t
res <- emmeans(mod, list(pairwise ~ Domestication*Fertilization), adjust = "fdr")
groups <- data.frame(multcomp::cld(res[[1]], adjust='fdr', Letters=c("abcdefghijklmnopqrstuvwxy"), decreasing=T))
groups <- groups %>%
  arrange(Fertilization, Domestication)

sum_shoot <-summarise(group_by(t3, Domestication,Fertilization),
  n = n(),
  mean = mean((P.ppm.)),
  sd = sd((P.ppm.)),
  se = sd/sqrt(n)) %>% 
  left_join(.,groups, by = c('Fertilization', 'Domestication'))
sum_shoot$.group <- gsub(' ','',sum_shoot$.group)
names(sum_shoot)[names(sum_shoot) == '.group'] <- 'letters'

p3<-ggplot(sum_shoot, aes(Domestication, mean, fill = Fertilization)) +
  geom_col(position = 'dodge') +
  geom_text(aes(label = letters),position=position_dodge(0.9), vjust = -.5, hjust = -0.2) +
  scale_fill_manual(values = c('#3498db','#f39c12'))+
  labs(y='Shoot Phosphorus Concentration (mg/kg)')+
  geom_errorbar(aes(ymin = mean-se, ymax = mean+se),position=position_dodge(0.9), width = .25)+
  ggtitle(label = 'Early Flower')+
  theme(axis.text=element_text(size=14, colour = "black"), 
        axis.title=element_text(size=12,face="bold"),
        axis.line = element_line(colour = "black"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        panel.background = element_blank(),
        axis.title.x = element_blank());p3

# t4
mod <- lm((P.ppm.) ~  Domestication*Fertilization, data=t4)
par(mfrow=c(2,2))
plot(mod)

aov.mod <- aov(mod)
summary(aov.mod)
t<-HSD.test(mod, "Domestication");t
t<-HSD.test(mod, "Fertilization");t
res <- emmeans(mod, list(pairwise ~ Domestication*Fertilization), adjust = "fdr")
groups <- data.frame(multcomp::cld(res[[1]], adjust='fdr', Letters=c("abcdefghijklmnopqrstuvwxy"), decreasing=T))
groups <- groups %>%
  arrange(Fertilization, Domestication)

sum_shoot <-summarise(group_by(t4, Domestication,Fertilization),
  n = n(),
  mean = mean((P.ppm.)),
  sd = sd((P.ppm.)),
  se = sd/sqrt(n))   %>% 
  left_join(.,groups, by = c('Fertilization', 'Domestication'))
sum_shoot$.group <- gsub(' ','',sum_shoot$.group)
names(sum_shoot)[names(sum_shoot) == '.group'] <- 'letters'

p4<-ggplot(sum_shoot, aes(Domestication, mean, fill = Fertilization)) +
  geom_col(position = 'dodge') +
  geom_text(aes(label = letters),position=position_dodge(0.9), vjust = -.5, hjust = -0.2) +
  scale_fill_manual(values = c('#3498db','#f39c12'))+
  labs(y='Shoot Phosphorus Concentration (mg/kg)')+
  geom_errorbar(aes(ymin = mean-se, ymax = mean+se),position=position_dodge(0.9), width = .25)+
  ggtitle(label = 'Late Flower')+
  theme(axis.text=element_text(size=14, colour = "black"), 
        axis.title=element_text(size=12,face="bold"),
        axis.line = element_line(colour = "black"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        panel.background = element_blank(),
        axis.title.x = element_blank(),
       legend.position = 'none');p4

# t5
mod <- lm((P.ppm.) ~  Domestication*Fertilization, data=t5)
par(mfrow=c(2,2))
plot(mod)

aov.mod <- aov(mod)
summary(aov.mod)

t<-HSD.test(mod, "Domestication");t
res <- emmeans(mod, list(pairwise ~ Domestication*Fertilization), adjust = "fdr")
groups <- data.frame(multcomp::cld(res[[1]], adjust='fdr', Letters=c("abcdefghijklmnopqrstuvwxy"), decreasing=T))
groups <- groups %>%
  arrange(Fertilization, Domestication)

sum_shoot <-summarise(group_by(t5, Domestication,Fertilization),
  n = n(),
  mean = mean((mg.kg)),
  sd = sd((mg.kg)),
  se = sd/sqrt(n))   %>% 
  left_join(.,groups, by = c('Fertilization', 'Domestication'))
sum_shoot$.group <- gsub(' ','',sum_shoot$.group)
names(sum_shoot)[names(sum_shoot) == '.group'] <- 'letters'

p5<-ggplot(sum_shoot, aes(Domestication, mean, fill = Fertilization)) +
  geom_col(position = 'dodge') +
  geom_text(aes(label = letters),position=position_dodge(0.9), vjust = -.5, hjust = -0.2) +
  scale_fill_manual(values = c('#3498db','#f39c12'))+
  labs(y='Shoot P Concentration (mg/kg)')+
  geom_errorbar(aes(ymin = mean-se, ymax = mean+se),position=position_dodge(0.9), width = .25)+
  ggtitle(label = 'Fruit')+
  theme(axis.text=element_text(size=14, colour = "black"), 
        axis.title=element_text(size=12,face="bold"),
        axis.line = element_line(colour = "black"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        panel.background = element_blank(),
        axis.title.x = element_blank(),
       legend.position = 'none');p5
ggarrange(p2, p3, p4, p5, ncol=2, nrow=2, common.legend = TRUE, legend="none")
```

# P content
```{r}
d.sub <- filter(d, Harvest != 'Early_Veg')
mod <- lm(log(P_content) ~  Harvest*Fertilization*Domestication, data=d.sub)
par(mfrow=c(2,2))
plot(mod)
summary(mod)
co <- mod$coefficients

level_order <- factor(d.sub$Harvest, levels = c('Late_Veg','Early_Flower',"Late_Flower","Fruit"))
p <- ggplot(aes(group=Fertilization,x=level_order, y=(P_content)), data = d.sub) +
  geom_hline(yintercept = 0,color='gray50')+
  geom_line(stat='summary',fun='mean',color='black',size=1) +
  geom_smooth(aes(fill=Fertilization, color=Fertilization))+
  scale_fill_manual(values = c('#3498db','#f39c12'))+
  scale_color_manual(values = c('#3498db','#f39c12'))+
  facet_wrap(~Domestication, ncol=2)+
  theme_classic()+
  labs(y="Log-Transformed Shoot Phosphorus Content (mg)")+
  theme(legend.title = element_blank(),
        legend.position = 'right',
        axis.text = element_text(color='black'),
        axis.title.x = element_blank());p

p <- ggplot(aes(group=Domestication,x=level_order, y=(P.ppm.)), data = d.sub) +
  geom_hline(yintercept = 0,color='gray50')+
  geom_line(stat='summary',fun='mean',color='black',size=1) +
  geom_smooth(aes(fill=Domestication, color=Domestication))+
  scale_fill_manual(values = c('#3498db','#f39c12'))+
  scale_color_manual(values = c('#3498db','#f39c12'))+
  facet_wrap(~Fertilization, ncol=2)+
  theme_classic()+
  labs(y="Log-Transformed Shoot Phosphorus Content (mg)")+
  theme(legend.title = element_blank(),
        legend.position = 'right',
        axis.text = element_text(color='black'),
        axis.title.x = element_blank());p

```

```{r}

#t2
mod <- lm((P_content) ~  Domestication*Fertilization, data=t2)
par(mfrow=c(2,2))
plot(mod)
aov.mod <- aov(mod)
summary(aov.mod)
t<-HSD.test(mod, "Domestication");t
t<-HSD.test(mod, "Fertilization");t
res <- emmeans(mod, list(pairwise ~ Domestication*Fertilization), adjust = "fdr")
res
plot(res[[1]], horizontal=F)
groups <- data.frame(multcomp::cld(res[[1]], adjust='fdr', Letters=c("abcdefghijklmnopqrstuvwxy"), decreasing=T))
groups <- groups %>%
  arrange(Fertilization, Domestication)

sum_shoot <-summarise(group_by(t2, Domestication,Fertilization),
  n = n(),
  mean = mean((P_content)),
  sd = sd((P_content)),
  se = sd/sqrt(n))  %>% 
  left_join(.,groups, by = c('Fertilization', 'Domestication'))
sum_shoot$.group <- gsub(' ','',sum_shoot$.group)

names(sum_shoot)[names(sum_shoot) == '.group'] <- 'letters'

p2<-ggplot(sum_shoot, aes(Domestication, mean, fill = Fertilization)) +
  geom_col(position = 'dodge') +
  geom_text(aes(label = letters),position=position_dodge(0.9), vjust = -.5, hjust = -0.2) +
  scale_fill_manual(values = c('#3498db','#f39c12'))+
  labs(y='Shoot P (mg/kg)')+
  geom_errorbar(aes(ymin = mean-se, ymax = mean+se),position=position_dodge(0.9), width = .25)+
  ggtitle(label = 'Late Vegetative')+
  theme(axis.text=element_text(size=14, colour = "black"), 
        axis.title=element_text(size=12,face="bold"),
        axis.line = element_line(colour = "black"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        panel.background = element_blank(),
        axis.title.x = element_blank(),
       legend.position = 'none');p2
# t3
mod <- lm((P_content) ~  Domestication*Fertilization, data=t3)
par(mfrow=c(2,2))
plot(mod)
aov.mod <- aov(mod)
summary(aov.mod)
t<-HSD.test(mod, "Domestication");t
t<-HSD.test(mod, "Fertilization");t
res <- emmeans(mod, list(pairwise ~ Domestication*Fertilization), adjust = "fdr")
groups <- data.frame(multcomp::cld(res[[1]], adjust='fdr', Letters=c("abcdefghijklmnopqrstuvwxy"), decreasing=T))
groups <- groups %>%
  arrange(Fertilization, Domestication)

sum_shoot <-summarise(group_by(t3, Domestication,Fertilization),
  n = n(),
  mean = mean((P_content)),
  sd = sd((P_content)),
  se = sd/sqrt(n)) %>% 
  left_join(.,groups, by = c('Fertilization', 'Domestication'))
sum_shoot$.group <- gsub(' ','',sum_shoot$.group)
names(sum_shoot)[names(sum_shoot) == '.group'] <- 'letters'

p3<-ggplot(sum_shoot, aes(Domestication, mean, fill = Fertilization)) +
  geom_col(position = 'dodge') +
  geom_text(aes(label = letters),position=position_dodge(0.9), vjust = -.5, hjust = -0.2) +
  scale_fill_manual(values = c('#3498db','#f39c12'))+
  labs(y='Shoot Phosphorus Concentration (mg/kg)')+
  geom_errorbar(aes(ymin = mean-se, ymax = mean+se),position=position_dodge(0.9), width = .25)+
  ggtitle(label = 'Early Flower')+
  theme(axis.text=element_text(size=14, colour = "black"), 
        axis.title=element_text(size=12,face="bold"),
        axis.line = element_line(colour = "black"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        panel.background = element_blank(),
        axis.title.x = element_blank());p3

# t4
mod <- lm((P_content) ~  Domestication*Fertilization, data=t4)
par(mfrow=c(2,2))
plot(mod)

aov.mod <- aov(mod)
summary(aov.mod)
t<-HSD.test(mod, "Domestication");t
t<-HSD.test(mod, "Fertilization");t
res <- emmeans(mod, list(pairwise ~ Domestication*Fertilization), adjust = "fdr")
groups <- data.frame(multcomp::cld(res[[1]], adjust='fdr', Letters=c("abcdefghijklmnopqrstuvwxy"), decreasing=T))
groups <- groups %>%
  arrange(Fertilization, Domestication)

sum_shoot <-summarise(group_by(t4, Domestication,Fertilization),
  n = n(),
  mean = mean((P_content)),
  sd = sd((P_content)),
  se = sd/sqrt(n))   %>% 
  left_join(.,groups, by = c('Fertilization', 'Domestication'))
sum_shoot$.group <- gsub(' ','',sum_shoot$.group)
names(sum_shoot)[names(sum_shoot) == '.group'] <- 'letters'

p4<-ggplot(sum_shoot, aes(Domestication, mean, fill = Fertilization)) +
  geom_col(position = 'dodge') +
  geom_text(aes(label = letters),position=position_dodge(0.9), vjust = -.5, hjust = -0.2) +
  scale_fill_manual(values = c('#3498db','#f39c12'))+
  labs(y='Shoot Phosphorus Content (mg)')+
  geom_errorbar(aes(ymin = mean-se, ymax = mean+se),position=position_dodge(0.9), width = .25)+
  ggtitle(label = 'Late Flower')+
  theme(axis.text=element_text(size=14, colour = "black"), 
        axis.title=element_text(size=12,face="bold"),
        axis.line = element_line(colour = "black"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        panel.background = element_blank(),
        axis.title.x = element_blank(),
       legend.position = 'none');p4

# t5
mod <- lm((P_content) ~  Domestication*Fertilization, data=t5)
par(mfrow=c(2,2))
plot(mod)

aov.mod <- aov(mod)
summary(aov.mod)

t<-HSD.test(mod, "Domestication");t
t<-HSD.test(mod, "Fertilization");t
res <- emmeans(mod, list(pairwise ~ Domestication*Fertilization), adjust = "fdr")
groups <- data.frame(multcomp::cld(res[[1]], adjust='fdr', Letters=c("abcdefghijklmnopqrstuvwxy"), decreasing=T))
groups <- groups %>%
  arrange(Fertilization, Domestication)

sum_shoot <-summarise(group_by(t5, Domestication,Fertilization),
  n = n(),
  mean = mean((P_content)),
  sd = sd((P_content)),
  se = sd/sqrt(n))   %>% 
  left_join(.,groups, by = c('Fertilization', 'Domestication'))
sum_shoot$.group <- gsub(' ','',sum_shoot$.group)
names(sum_shoot)[names(sum_shoot) == '.group'] <- 'letters'

p5<-ggplot(sum_shoot, aes(Domestication, mean, fill = Fertilization)) +
  geom_col(position = 'dodge') +
  geom_text(aes(label = letters),position=position_dodge(0.9), vjust = -.5, hjust = -0.2) +
  scale_fill_manual(values = c('#3498db','#f39c12'))+
  labs(y='Shoot P Content (mg)')+
  geom_errorbar(aes(ymin = mean-se, ymax = mean+se),position=position_dodge(0.9), width = .25)+
  ggtitle(label = 'Fruit')+
  theme(axis.text=element_text(size=14, colour = "black"), 
        axis.title=element_text(size=12,face="bold"),
        axis.line = element_line(colour = "black"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        panel.background = element_blank(),
        axis.title.x = element_blank(),
       legend.position = 'none');p5
ggarrange(p2, p3, p4, p5, ncol=2, nrow=2, common.legend = TRUE, legend="none")
```

# Percent change
```{r}
df <- read.csv('Data/P_Concentration_Percent_Change.csv')

t2 <- filter(df, Harvest == 'Late_Veg')
t3 <- filter(df, Harvest == 'Early_Flower')
t4 <- filter(df, Harvest == 'Late_Flower')
t5 <- filter(df, Harvest == 'Fruit')

#t3
mod <- lm((pchange) ~  Domestication, data=t3)
par(mfrow=c(2,2))
plot(mod)

aov.mod <- aov(mod)
summary(aov.mod)

t<-HSD.test(mod, "Domestication");t
sum_shoot <-summarise(group_by(t4, Domestication,Fertilization),
  n = n(),
  mean = mean((pchange)),
  sd = sd((pchange)),
  se = sd/sqrt(n))  
sum_shoot$letters <- c('a','b')

p7<-ggplot(sum_shoot, aes(Domestication, mean, fill = Domestication)) +
  geom_col(position = 'dodge') +
  geom_text(aes(label = letters),position=position_dodge(0.9), vjust = -.5, hjust = -0.2) +
  scale_fill_manual(values = c('#3498db','#f39c12'))+
  labs(y='Percent Change (%)')+
  geom_errorbar(aes(ymin = mean-se, ymax = mean+se),position=position_dodge(0.9), width = .25)+
  ggtitle(label = 'Late Flower')+
  theme(axis.text=element_text(size=14, colour = "black"), 
        axis.title=element_text(size=12,face="bold"),
        axis.line = element_line(colour = "black"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        panel.background = element_blank(),
        axis.title.x = element_blank(),
       legend.position = 'none');p7

#t5
mod <- lm((pchange) ~  Domestication, data=t5)
par(mfrow=c(2,2))
plot(mod)

aov.mod <- aov(mod)
summary(aov.mod)

t<-HSD.test(mod, "Domestication");t
sum_shoot <-summarise(group_by(t5, Domestication,Fertilization),
  n = n(),
  mean = mean((pchange)),
  sd = sd((pchange)),
  se = sd/sqrt(n))  
sum_shoot$letters <- c('a','a')

p8<-ggplot(sum_shoot, aes(Domestication, mean, fill = Domestication)) +
  geom_col(position = 'dodge') +
  geom_text(aes(label = letters),position=position_dodge(0.9), vjust = -.5, hjust = -0.2) +
  scale_fill_manual(values = c('#3498db','#f39c12'))+
  labs(y='Percent Change (%)')+
  geom_errorbar(aes(ymin = mean-se, ymax = mean+se),position=position_dodge(0.9), width = .25)+
  ggtitle(label = 'Early Flower')+
  theme(axis.text=element_text(size=14, colour = "black"), 
        axis.title=element_text(size=12,face="bold"),
        axis.line = element_line(colour = "black"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        panel.background = element_blank(),
        axis.title.x = element_blank(),
       legend.position = 'none');p8
```

