---
title: "P_cycling_bacteria"
author: "MD"
date: "`r Sys.Date()`"
output: 
 html_document:
   toc: true
   toc_float: true
   editor_options:
   chunck_output_type: console
   chunk_output_type: console
---

# Load libraries
```{r}
library(vegan)
library(pairwiseAdonis)
library(RColorBrewer)
library(microbiomeMarker)
library(tidyverse)
library(phyloseq)
library(readxl)
library(emmeans)
library(agricolae)
library(car)
library(patchwork)
```

# Setup
## Read in data
```{r}
kegg <- read_excel('Data/EMU_database.GIBBs.KO.PICRUST2.xlsx', sheet='EMU_database.GIBBs.PICRUSt2', range='B9:BE17565')
kegg <- kegg %>%
  mutate_if(is.numeric, replace_na, replace=0)

P.rel <- readRDS('phyloseq/P.Time.rel.RDS')
P.rel <- subset_samples(P.rel, Reads.16S > 10000)

```



# P decomposers
```{r}
wanted <- kegg[kegg$phoA > 0 | kegg$phoD > 0 | kegg$PHO > 0 | kegg$appA > 0 | kegg$phoN > 0 ,  ]$Species
P.sub <- subset_taxa(P.rel, Species %in% wanted)

P.glom <- tax_glom(P.sub, taxrank="Species")
P.glom <- prune_taxa(taxa_sums(P.glom) > 0, P.glom)
pdecomp <- psmelt(P.glom) %>% 
  filter(., Abundance != 0)
options(contrasts = c("contr.sum", "contr.poly"))

pdecomp <- pdecomp %>%
mutate(Stage = as_factor(Stage)) %>%
mutate(Stage = fct_relevel(Stage, "Seedling", "Early_Vegetative", "Late_Vegetative", "Early_Flower", "Late_Flower"))
table(pdecomp$Stage)

pdecomp <- pdecomp %>%
mutate(Fertilization = as_factor(Fertilization)) %>%
mutate(Fertilization = fct_relevel(Fertilization, "Unfertilized", "Fertilized"))
```

# Run model (log transform needed)
```{r}
mod <- lm(log(Abundance) ~  Stage*Fertilization*Domestication, data=pdecomp)
par(mfrow=c(2,2))
plot(mod)
t <- HSD.test(mod, "Fertilization");t
t <- HSD.test(mod, "Domestication");t
t <- HSD.test(mod, "Stage");t
Anova(mod, type = 3)
emmip(mod, Domestication ~ Stage | Fertilization, CIs = TRUE, type = "response")# type = response shows backtransformed 

emmeans(mod, pairwise ~ Domestication|Stage|Fertilization)
emmeans(mod, ~ Fertilization*Domestication*Stage, type = "response")
df <- as.data.frame(emmeans(mod, ~ Fertilization*Domestication*Stage, type = "response"))

res <- emmeans(mod, list(pairwise ~ Fertilization*Domestication*Stage), adjust = "fdr")
plot(res[[1]], horizontal=T)
groups <- data.frame(multcomp::cld(res[[1]], adjust='fdr', Letters=c("abcdefghijklmnopqrstuvwxy"), decreasing=T)) %>% 
  select(., Fertilization, Domestication, Stage, .group)
df <- inner_join(df,groups, by = c('Fertilization', 'Domestication', 'Stage'))

names(df)[names(df) == '.group'] <- 'letters'
df$letters <- gsub(' ','',df$letters)
```



### Data visualization
```{r}
df.decf <- filter(df, Fertilization== "Fertilized")
df.decu <- filter(df, Fertilization== "Unfertilized")
p_df<- ggplot(aes(x=Stage, y=response), data = df.decf) +
  geom_line(aes(color=Domestication, group=Domestication),
            stat='summary',fun='mean',linewidth=1) +
  geom_errorbar(width=0.25,alpha=0.5,
                aes(ymin = lower.CL, ymax = upper.CL, 
                    group=Domestication,color=Domestication))+
  scale_color_manual(values = c('darkblue','darkorange2'))+
  geom_text(aes(label = letters),position=position_dodge(0.9), vjust = -3, hjust = -0.2) +
  theme_classic()+
 ylab(expression(atop("Relative Abundance", paste("(Phosphorus Mineralizing Bacteria)")))) +
  theme(legend.title = element_blank(),
        strip.text = element_blank(),
        legend.position = 'right',
        axis.text = element_text(color='black'),
        axis.title.x = element_blank());p_df

#ggsave(plot=p_df, '../../Manuscript/figs/R_output/relabund_p_min.png', width = 8, height = 4)
```


# Select P solubilizer
```{r}
wanted <- kegg[kegg$pqqC > 0 ,  ]$Species
P.sub <- subset_taxa(P.rel, Species %in% wanted)

P.glom <- tax_glom(P.sub, taxrank="Species")
P.glom <- prune_taxa(taxa_sums(P.glom) > 0, P.glom)
psol <- psmelt(P.glom) %>% 
  filter(., Abundance != 0)
psol <- psol %>%
mutate(Stage = as_factor(Stage)) %>%
mutate(Stage = fct_relevel(Stage, "Seedling", "Early_Vegetative", "Late_Vegetative", "Early_Flower", "Late_Flower"))
table(psol$Stage)

psol <- psol %>%
mutate(Fertilization = as_factor(Fertilization)) %>%
mutate(Fertilization = fct_relevel(Fertilization, "Unfertilized", "Fertilized"))

```


# Run model (log transform needed)
```{r}
mod <- lm(log(Abundance) ~  Stage*Fertilization*Domestication, data=psol)
par(mfrow=c(2,2))
plot(mod)

Anova(mod, type = 3)
t <- HSD.test(mod, "Fertilization");t
emmip(mod, Domestication ~ Stage | Fertilization, CIs = TRUE, type = "response")# type = response shows backtransformed 

emmeans(mod, pairwise ~ Domestication|Stage|Fertilization)
emmeans(mod, ~ Fertilization*Domestication*Stage, type = "response")
df <- as.data.frame(emmeans(mod, ~ Fertilization*Domestication*Stage, type = "response"))

res <- emmeans(mod, list(pairwise ~ Fertilization*Domestication*Stage), adjust = "fdr")
plot(res[[1]], horizontal=T)
groups <- data.frame(multcomp::cld(res[[1]], adjust='fdr', Letters=c("abcdefghijklmnopqrstuvwxy"), decreasing=T)) %>% 
  select(., Fertilization, Domestication, Stage, .group)
df <- inner_join(df,groups, by = c('Fertilization', 'Domestication', 'Stage'))

names(df)[names(df) == '.group'] <- 'letters'
df$letters <- gsub(' ','',df$letters)
```


### Data visualization
```{r}
df.solf <- filter(df, Fertilization == "Fertilized")
df.solu <- filter(df, Fertilization == "Unfertilized")
p_sf <- ggplot(aes(x=Stage, y=response), data = df.solf) +
  geom_line(aes(color=Domestication, group=Domestication),
            stat='summary',fun='mean',size=1) +
  geom_errorbar(width=0.25,alpha=0.5,
                aes(ymin = lower.CL, ymax = upper.CL, 
                    group=Domestication,color=Domestication))+
  scale_color_manual(values = c('darkblue','darkorange2'))+
  geom_text(aes(label = letters),position=position_dodge(0.9), vjust = -3, hjust = -0.2) +
  theme_classic()+
 ylab(expression(atop("Relative Abundance", paste("(Phosphorus Solubilizing Bacteria)")))) +
  theme(legend.title = element_blank(),
        legend.position = 'right',
        axis.text.x = element_blank(),
        axis.text = element_text(color='black'),
        axis.title.x = element_blank());p_sf

#ggsave(plot=p_sf, '../../Manuscript/figs/R_output/relabund_solubilizer.png', width = 8, height = 4)
```

Run qpcr before running this code chunk

```{r}
p_bac <- (p_sf+p_df)/ (p_cf + p_f) + plot_layout(axes = "collect")+ plot_layout(guides = "collect"); p_bac
#ggsave(plot=p_bac, '../../Manuscript/figs/R_output/3_sol_dec_bioc_qpcr.png', width = 12, height =6)

p_bacu <- (p_su+p_du)/ (p_cu + p_u) + plot_layout(axes = "collect")+ plot_layout(guides = "collect"); p_bacu
#ggsave(plot=p_bacu, '../../Manuscript/figs/R_output/s3_unfert_sol_dec_bioc_qpcr.png', width = 12, height =6)

```

